import sys
import os
import yaml
import pandas as pd

sys.path.append(os.path.abspath('/Users/jimmyswindler/Desktop/MarcomProductionWorkshop'))
from shared_lib.database import get_db_connection, get_real_dict_cursor
from shared_lib.ingest_helpers import calculate_box_requirements

def backfill_missing_boxes():
    conn = get_db_connection()
    cur = get_real_dict_cursor(conn)

    with open('/Users/jimmyswindler/Desktop/MarcomProductionWorkshop/config/config.yaml', 'r') as f:
        config = yaml.safe_load(f)

    # Find all items that have NO entry in item_boxes
    cur.execute("""
        SELECT i.order_item_id, i.product_id, i.quantity_ordered, j.job_ticket_number
        FROM items i
        JOIN jobs j ON i.job_id = j.id
        LEFT JOIN item_boxes b ON i.order_item_id = b.order_item_id
        WHERE b.id IS NULL
    """)
    rows = cur.fetchall()
    
    if not rows:
        print("No items found missing box records.")
        return

    print(f"Found {len(rows)} items missing box records. Simulating ingest box requirements...")
    
    df = pd.DataFrame(rows)
    df_out = calculate_box_requirements(df, config)
    
    # Track how many boxes we actually intend to insert
    inserts = []
    
    for idx, row in df_out.iterrows():
        oid = row['order_item_id']
        for i in range(8):
            col = f'box_{chr(65+i)}'
            barcode = row.get(col)
            if barcode:
                inserts.append((oid, i+1, barcode))
    
    print(f"Generated {len(inserts)} specific item_box insertions.")
    
    if inserts:
        # Perform batched insert
        cur.executemany("""
            INSERT INTO item_boxes (order_item_id, box_sequence, barcode_value)
            VALUES (%s, %s, %s)
            ON CONFLICT DO NOTHING
        """, inserts)
        
        conn.commit()
        print("Backfill applied successfully.")
    else:
        print("No item boxes were actually generated by the rules for the missing items.")
        
    conn.close()

if __name__ == '__main__':
    backfill_missing_boxes()
